name: Status

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-commit-targets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download previous status artifact
      id: download_status
      uses: actions/download-artifact@v3
      with:
        name: server-status
        path: .
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        ROCKET_CHAT_INSTANCE: ${{ secrets.ROCKET_CHAT_INSTANCE }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REPOSITORIES: ${{ secrets.REPOSITORIES }}
        USER_MAPPING: ${{ secrets.USER_MAPPING }}
      run: python main.py --status

    - name: Upload status artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: server-status
        path: status.txt
