name: Status

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  server-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Download previous status artifact
    #   id: download_status
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: server-status
    #     path: .
    #   continue-on-error: true

    - name: Download previous status artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: status.yml
        workflow_conclusion: success
        name: server-status
      continue-on-error: true

    - name: Display previous status
      if: success()
      run: |
        if [ -f server_status.txt ]; then
          echo "Previous status:"
          cat server_status.txt
        else
          echo "No previous status found."
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        ROCKET_CHAT_INSTANCE: ${{ secrets.ROCKET_CHAT_INSTANCE }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REPOSITORIES: ${{ secrets.REPOSITORIES }}
        USER_MAPPING: ${{ secrets.USER_MAPPING }}
      run: python main.py --status

    - name: Upload status artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: server-status
        path: server_status.txt
